### ISSUE TITLE
Please Add License

### ISSUE THREAD

**Issue by aarongreenlee** [jmcvetta/restclient#2]
Hello, 

Your project has been included as a dependency to another package and I was hoping you could update this package to include a license. I understand this package is no longer in development.

Can you please add a license file? This helps automated scanners.

Thanks,

Aaron Greenlee

**Comment by jmcvetta** [comment]
Hi Aaron,

Just out of curiosity, why are you using a deprecated package?  `restclient` has not been updated in years, and is no longer maintained.  Instead please consider [Napping](http://github.com/jmcvetta/napping), the successor to `restclient`.  

As for the license:

``` bash
$ head -4 client.go 
// Copyright (c) 2012-2013 Jason McVetta.  This is Free Software, released
// under the terms of the GPL v3.  See http://www.gnu.org/copyleft/gpl.html for
// details.  Resist intellectual serfdom - the ownership of ideas is akin to
// slavery.
```

**Comment by aarongreenlee** [comment]
It was included as a dependency to another package one of my team members
recently vendored.
